### ISSUE TITLE
Could you document a little bit of theory?

### ISSUE THREAD

**Issue by realtebo** [cyrilwanner/next-compose-plugins#14]
I'm here to ask devleoper help to understand what must be done and where and how when adding 'translating' the default configuration of a plugin of webpack  to your plugin syntax. 

Example: 

I can simply run sass using

```
const withPlugins = require('next-compose-plugins');


const nextConfig = ({
  webpack: async (config, options) => {
    return config;
  },
});


const plugins = [
  
  [NextSassPlugin],
  
];

// plugins: array
// nextConfig: un oggetto
module.exports = withPlugins (
  [...plugins], 
  nextConfig 
);

```

is this right?

I see that this single step create (in dev mode) `.next/static/css/style.chunk.css` and its complementar `.map`. 

Then I'd like to add for example [Optimize Css Assets Plugi](https://github.com/NMFR/optimize-css-assets-webpack-plugin)

I tried with a simple 
```

const NextSassPlugin = require("@zeit/next-sass");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");
const withPlugins    = require('next-compose-plugins');

const nextConfig = ({
  webpack: async (config, options) => {
    return config;
  },
});

const plugins = [
  
  [NextSassPlugin],
  [OptimizeCssAssetsPlugin]

];

// plugins: array
// nextConfig: un oggetto
module.exports = withPlugins (
  [...plugins], 
  nextConfig 
);

```

But I got a crash:

> TypeError: Class constructor OptimizeCssAssetsWebpackPlugin cannot be invoked without 'new'
    at plugins.forEach.plugin (.....\node_modules\next-compose-plugins\lib\compose.js:102:23)
    at Array.forEach (<anonymous>)
    at composePlugins (.....\node_modules\next-compose-plugins\lib\compose.js:79:11)
    at .....\node_modules\next-compose-plugins\lib\index.js:22:38
    at loadConfig (.....\node_modules\next\dist\server\config.js:54:10)

I lloked at other plugin docs and tried using `new()`

```
const plugins = [
  
  [NextSassPlugin],
  [new OptimizeCSSAssetsPlugin()]

];
```

Now `npm run dev` doesn't crash, but nothing happe to the target file,  `styles.chunk.css`.

I exited crazy trying to understand how to simple add a test and add a loader to webpack config. I ended in this, but I do not see any difference, so I cannot understand where/how myconfig must be fixed.
```

const NextSassPlugin = require("@zeit/next-sass");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const withPlugins    = require('next-compose-plugins');

const nextConfig = ({
  webpack: async (config, options) => {
    config.module.rules.push({
      test: /\.css$/,
      loader: MiniCssExtractPlugin.loader
    });
    return config;
  },
});

const plugins = [
  
  [NextSassPlugin],
  [new OptimizeCSSAssetsPlugin()]

];

// plugins: array
// nextConfig: un oggetto
module.exports = withPlugins (
  [...plugins], 
  nextConfig 
);



```
So this is my actual problem, but I widened the broad of my request

The title of this issue is due to a request I'd open to you: please, document the logical process of understand where/how to add test, loader, optimizations and other webpack configs, explaining when to use 

```
[pluginName, {pluginConfig}]
```

and when/how/where add these configs to 

```
const nextConfig = ({
  webpack: async (config, options) => {
    .... here .... ? where, when, how ?
    return config;
  },
});
```

**Comment by realtebo** [comment]
First of all, thanks: for reply, for big explanation effort and for the plugin itself. 

I appreciated your explanation about next.js plugins vs webpack 'native' plugins, this difference was totally not clear to me.

But you focus so much on my specific problem that you loose my goal, understand how to integrate an external, no-nextjs,  plugin, a webpack plugin, when using your plugin. 

Imagine I want to use a totally different one, one not 'overlapping' the one I am already using....

My question is still valid, sorry. How to do this?

**Comment by realtebo** [comment]
Ok, that's very usefull, thanks.
